# Generated by Django 3.1.3 on 2020-12-10 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Orderline',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('qty', models.IntegerField(blank=True, db_column='Qty', null=True)),
                ('customerid', models.ForeignKey(blank=True, db_column='CustomerId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dbms_app.customer')),
            ],
            options={
                'db_table': 'orderline',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=255, null=True)),
                ('orderid', models.ForeignKey(db_column='OrderId', on_delete=django.db.models.deletion.DO_NOTHING, to='dbms_app.orderline')),
            ],
            options={
                'db_table': 'product',
                'unique_together': {('id', 'orderid')},
            },
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
            ],
            options={
                'db_table': 'sales_person',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('supplierid', models.ForeignKey(blank=True, db_column='SupplierId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dbms_app.supplier')),
            ],
            options={
                'db_table': 'part',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='sales_personid',
            field=models.ForeignKey(blank=True, db_column='Sales_personId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dbms_app.salesperson'),
        ),
        migrations.CreateModel(
            name='ProductPart',
            fields=[
                ('productid', models.OneToOneField(db_column='ProductId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dbms_app.product')),
                ('partid', models.ForeignKey(db_column='PartId', on_delete=django.db.models.deletion.DO_NOTHING, to='dbms_app.part')),
            ],
            options={
                'db_table': 'product_part',
                'unique_together': {('productid', 'partid')},
            },
        ),
        migrations.CreateModel(
            name='Assembling',
            fields=[
                ('productid', models.OneToOneField(db_column='ProductId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dbms_app.product')),
                ('employeeid', models.ForeignKey(db_column='EmployeeId', on_delete=django.db.models.deletion.DO_NOTHING, to='dbms_app.employee')),
            ],
            options={
                'db_table': 'assembling',
                'unique_together': {('productid', 'employeeid')},
            },
        ),
    ]
