# Generated by Django 3.1.3 on 2020-12-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms_app', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
