# Generated by Django 3.1.3 on 2020-12-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms_app', '0004_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembling',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='supplied',
            field=models.BooleanField(default=False),
        ),
    ]
