# Generated by Django 3.1.3 on 2020-12-11 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbms_app', '0005_auto_20201211_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembling',
            name='employeeid',
            field=models.ForeignKey(db_column='EmployeeId', on_delete=django.db.models.deletion.CASCADE, to='dbms_app.employee'),
        ),
        migrations.AlterField(
            model_name='assembling',
            name='productid',
            field=models.OneToOneField(db_column='ProductId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dbms_app.product'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sales_personid',
            field=models.ForeignKey(blank=True, db_column='Sales_personId', null=True, on_delete=django.db.models.deletion.CASCADE, to='dbms_app.salesperson'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='customerid',
            field=models.ForeignKey(blank=True, db_column='CustomerId', null=True, on_delete=django.db.models.deletion.CASCADE, to='dbms_app.customer'),
        ),
        migrations.AlterField(
            model_name='part',
            name='supplierid',
            field=models.ForeignKey(blank=True, db_column='SupplierId', null=True, on_delete=django.db.models.deletion.CASCADE, to='dbms_app.supplier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='orderid',
            field=models.ForeignKey(db_column='OrderId', on_delete=django.db.models.deletion.CASCADE, to='dbms_app.orderline'),
        ),
        migrations.AlterField(
            model_name='productpart',
            name='partid',
            field=models.ForeignKey(db_column='PartId', on_delete=django.db.models.deletion.CASCADE, to='dbms_app.part'),
        ),
        migrations.AlterField(
            model_name='productpart',
            name='productid',
            field=models.OneToOneField(db_column='ProductId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dbms_app.product'),
        ),
    ]
