# Generated by Django 3.1.3 on 2020-12-12 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbms_app', '0006_auto_20201211_1230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPart',
        ),
    ]
