# Generated by Django 3.1.3 on 2020-12-12 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbms_app', '0007_delete_productpart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partid', models.ForeignKey(db_column='PartId', on_delete=django.db.models.deletion.CASCADE, to='dbms_app.part')),
                ('productid', models.ForeignKey(db_column='ProductId', on_delete=django.db.models.deletion.CASCADE, to='dbms_app.product')),
            ],
            options={
                'db_table': 'product_part',
            },
        ),
    ]
